version: '3.8'

services:
  pyfinder_dgen:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    container_name: pyfinder_dgen
    volumes:
      - ./output:/app/output
    environment:
      - OUTPUT_DIR=/app/output
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
